### ISSUE TITLE
json2.DecodeClientResponse panic if result is null

### ISSUE THREAD

**Issue by sosedoff** [gorilla/rpc#28]
Method panics with invalid memory address when `result` attribute of RPC response is set to `null`.

Example data:

```json
{"jsonrpc": "2.0", "id": 8674665223082153551, "result": null}
```

Example code:

```go
package main

import (
	"bytes"
	"fmt"

	rpc "github.com/gorilla/rpc/v2/json2"
)

func main() {
	data := `{"jsonrpc": "2.0", "id": 8674665223082153551, "result": null}`
	reader := bytes.NewReader([]byte(data))

	var reply interface{}

	err := rpc.DecodeClientResponse(reader, &reply)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(reply)
}
```

**Comment by kisielk** [comment]
Technically the result should never be null unless there is an error, but we shouldn't be panicking here.

**Comment by sosedoff** [comment]
I checked with http://www.jsonrpc.org/specification, it does not say anything about `null` values.
The issue appeared while working with mopidy's rpc - https://docs.mopidy.com/en/latest/api/http/

**Comment by kisielk** [comment]
http://www.jsonrpc.org/specification#response_object

"This member is REQUIRED on success."

Does null still count as being included?

**Comment by sosedoff** [comment]
Null is a legit json value. I think in this case REQUIRED means that `result` key is present in the response.

**Comment by kisielk** [comment]
hm ok, but if you are decoding the result in to a struct for example, how should we signal a null result?

I think returning a specific error value, eg ErrNullResult is the only way we can do it with the current API. What do you think?

**Comment by sosedoff** [comment]
Here's my branch with the proposed fix: https://github.com/sosedoff/rpc/tree/v2-unmarshal-fix
Added a quick test to verify it works. Let me know if you need a PR

Regarding decoding into a struct, when result is set to `null` it should not affect the struct
since there's simply no data to decode. I agree that this could be problematic for a user to 
detect, but jsonrpc is dealing with data of any kind in the `result` attribute anyway.

**Comment by kisielk** [comment]
okay that works. I still think in the majority of cases you wouldn't be passing an interface{} in to the function but rather a struct which would allow the expected result to be filled in. It would be nice if there was an error to signal that nothing was returned, as opposed to not being able to tell the difference between null and some fields being present but 0.

**Comment by sosedoff** [comment]
Alright then. I can add this behavior to the PR

**Comment by kisielk** [comment]
yeah, let's make a value called ErrNullResult and return that if there's nothing to decode.

**Comment by sosedoff** [comment]
Done, see #30
