### ISSUE TITLE
HTTP status code is written before content type is set

### ISSUE THREAD

**Issue by yolofy** [gorilla/rpc#38]
File: github.com/gorilla/rpc/v2/protorpc/server.go

The header status is written before the content type is set. Thus is has no effect, please set the content type before writing the status code.

```go
func (c *CodecRequest) writeServerResponse(w http.ResponseWriter, status int, res *serverResponse) {
    b, err := json.Marshal(res.Result)
    if err == nil {
        w.WriteHeader(status)
        w.Header().Set("Content-Type", "application/json; charset=utf-8")
        w.Write(b)
    } else {
        // Not sure in which case will this happen. But seems harmless.
        rpc.WriteError(w, 400, err.Error())
    }
}
```
should be

```go
func (c *CodecRequest) writeServerResponse(w http.ResponseWriter, status int, res *serverResponse) {
    b, err := json.Marshal(res.Result)
    if err == nil {
        w.Header().Set("Content-Type", "application/json; charset=utf-8")
        w.WriteHeader(status)
        w.Write(b)
    } else {
        // Not sure in which case will this happen. But seems harmless.
        rpc.WriteError(w, 400, err.Error())
    }
}
```

**Comment by elithrar** [comment]
Thanks for the bug report @yolofy. In this case Go (1.5) correctly sniffs MIME type and sets the `Content-Type` header correctly, but I've added a test case and fixed the header write order in a PR.

**Comment by elithrar** [comment]
Merged.

**Comment by yolofy** [comment]
In my case it wasn't set correctly. I'm using Go 1.5.1 on OS X El Capitan
10.11.1. Perhaps it's also a Go issue.

2015-11-04 23:25 GMT+01:00 Matt Silverlock <notifications@github.com>:
