### ISSUE TITLE
Versions and tags

### ISSUE THREAD

**Issue by henti** [gorilla/rpc#49]
Hi there,

I'm busy packaging rpc for Debian as a dependency for minio. For packaging to work correctly, we need to be able to scan for updated versions, and for that we need releases or tags. Please read https://wiki.debian.org/debian/watch and specifically https://wiki.debian.org/debian/watch#GitHub for more information on tags/release information in github that is needed to make packaging easier.

Can you please tag or release your software accordingly.

Regards
Henti

**Comment by elithrar** [comment]
Hi there - neither of those links describe suitable versioning schemes
(there is no mention of "SemVer" at all, for example) and instead just show
regex you might use to parse versions.

I'm going to presume that SemVer is acceptable.

**Comment by henti** [comment]
Hi there, 

You are correct, neither link details versioning schemes. The links were to illustrate the missing information to properly detect new versions of your software to allow easy packaging. 

As long as there is some versioning tags I'll make sure the regex works to detect new versions as they get tagged/released. 

Regards
Henti

**Comment by henti** [comment]
@elithrar any update on this? I'm done with all the packaging and would like to submit the package to Debian for inclusion.

**Comment by elithrar** [comment]
@henti Tagged. I am concerned that this being packaged on Debian will island package users from upstream updates (because there will be an intermediary in the mix) + `go get` exists, but I probably can't convince you otherwise here!

**Comment by henti** [comment]
@elithrar Thank you, 

While I understand your concern regarding upstream updates, once packaged, it does mean I will actively try to maintain it and any security patches will be applied and updated to Debian. 

New features will have to wait for a new release cycle of Debian. 

This is the unfortunate situation of packaging for popular distributions, but also does makes it easily manageable within Debian, which is my objective.
