### ISSUE TITLE
Error from json.Encode is ignored

### ISSUE THREAD

**Issue by giniedp** [gorilla/rpc#57]
The call to encoder.Encode() does return an error but it is ignored here
https://github.com/gorilla/rpc/blob/master/json/server.go#L133
It has the effect that the json body is not written but the response is still annotated with Content-Type application/json.

**Comment by kisielk** [comment]
Yes you're right, looks like that should be assigned to `c.err` and then `c.err` returned at the end of the method. Do you want to submit a PR?

**Comment by giniedp** [comment]
here you go
