### ISSUE TITLE
expose a method to support CORS

### ISSUE THREAD

**Issue by m3ngyang** [gorilla/rpc#74]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

In some circumstance, we ask the server to allow CORS, but jsonrpc doesn't support it now.

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

…

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

…

**Comment by elithrar** [comment]
See comments in #75.
