### ISSUE TITLE
[bug] invalid version

### ISSUE THREAD

**Issue by liuxh-go** [gorilla/rpc#78]
**Describe the bug**
> when i use go mod download,err:
> go: finding github.com/gorilla/rpc v1.2.0+incompatible
> github.com/gorilla/rpc@v1.2.0+incompatible: invalid version: +incompatible suffix not allowed: major version v1 is compatible

**Versions**
> Go version: `go1.13.5 darwin/amd64`
> package version: v1.2.0

**Steps to Reproduce**
> use go mod download

**Comment by shravanshetty1** [comment]
Any updates on this?

**Comment by shanebarnes** [comment]
Also curious if there are any plans to address this issue.

I have also seen this issue on go1.13.x and go1.14.x:

`go list -m: github.com/gorilla/rpc@v1.2.0+incompatible: invalid version: +incompatible suffix not allowed: major version v1 is compatible`
